envs:
  - TicTacToeTeam-v0-train
  - ConnectFourTeam-v0-train
  - BreakthroughTeam-v0-small-train
games: 64
concurrency: 240
error_allowance: 3
dry_run: false
backend: openrouter
api_key: ${OPENROUTER_API_KEY}

temperature: 0.7
top_p: 0.95
timeout: 540.0

team_sampler:
  sample: 'bradley_terry'
  teams:
    GPT-5.4-Nano-Reflection:
      type: reflection
      rounds: 3
      agents:
        Robert: openai/gpt-5.4-nano
    GPT-5.4-Nano-Cooperation-2:
      type: voting
      rounds: 3
      agents:
        Robert: openai/gpt-5.4-nano
        Alice: openai/gpt-5.4-nano
    GPT-5.4-Nano-Cooperation-3:
      type: voting
      rounds: 3
      agents:
        Robert: openai/gpt-5.4-nano
        Alice: openai/gpt-5.4-nano
        Bob: openai/gpt-5.4-nano
    GPT-5.4-Nano-Cooperation-4:
      type: voting
      rounds: 3
      agents:
        Robert: openai/gpt-5.4-nano
        Alice: openai/gpt-5.4-nano
        Bob: openai/gpt-5.4-nano
        Charlie: openai/gpt-5.4-nano