env: TicTacToeTeam-v0-train
games: 200
concurrency: 100
dry_run: false
backend: vllm_actor
template: hf

actor:
  num_slots: 4
  num_gpus_per_slot: 1
  max_model_len: 32000
  max_num_seqs: 40
  max_tokens: 30000
  gpu_memory_utilization: 0.85
  temperature: 0.7
  top_p: 0.95
  top_k: 50

team_sampler:
  sample: 'elo'
  teams:
    Single:
      type: reflection
      rounds: 4
      agents:
        Robert: openai/gpt-oss-20b
    Two:
      type: voting
      rounds: 2
      agents:
        Robert: openai/gpt-oss-20b
        Alice: openai/gpt-oss-20b
    Three:
      type: voting
      rounds: 2
      agents:
        Robert: openai/gpt-oss-20b
        Alice: openai/gpt-oss-20b
        Bob: openai/gpt-oss-20b
    Four:
      type: voting
      rounds: 2
      agents:
        Robert: openai/gpt-oss-20b
        Alice: openai/gpt-oss-20b
        Bob: openai/gpt-oss-20b
        Carol: openai/gpt-oss-20b